# Generated by Django 5.1.4 on 2024-12-20 16:35

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=builtins.print),
            preserve_default=False,
        ),
    ]
