# Generated by Django 5.1.4 on 2024-12-20 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='quantity',
        ),
    ]
