# Generated by Django 5.1.4 on 2024-12-24 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_remove_products_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
